import { app, BrowserWindow, ipcMain, Menu, protocol, net } from 'electron';
import path from 'path';
import { pathToFileURL } from 'url';
import { autoUpdater } from 'electron-updater';
import DataSourceConfigurator from './electron/DataSourceConfigurator';
import { isDev } from './electron/util';
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

protocol.registerSchemesAsPrivileged([
  { scheme: 'pos-pdf', privileges: { bypassCSP: true, stream: true, secure: true, supportFetchAPI: true } }
]);

const dataSourceConfigurator = new DataSourceConfigurator(ipcMain);



const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    icon: path.join(__dirname, 'icons', 'icon.ico'),
    height: 600,
    width: 800,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY
    },
  });

  // and load the index.html of the app.
  if (isDev()) {
    mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
  } else {
    mainWindow.loadFile(path.join(__dirname, '..', 'renderer', 'main_window', 'index.html'));
  }

  Menu.setApplicationMenu(null);
  // Open the DevTools.
  if (isDev()) {
    mainWindow.webContents.openDevTools();
  }
};

function createMainWindow() {
  dataSourceConfigurator.configure()
    .then(() => {
      createWindow();
    })
    .catch(error => {
      console.error('Error initializing database:', error);
      app.quit();
    });
}

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', () => {
  protocol.handle('pos-pdf', (request) => {
    try {
      const url = new URL(request.url);
      const filename = url.pathname.startsWith('/') ? url.pathname.slice(1) : url.pathname;
      const folderPath = isDev() ? path.join(process.cwd(), 'cotizations-pdfs') : path.join(app.getPath('userData'), 'cotizations-pdfs');
      const filePath = path.join(folderPath, filename);
      console.log(`Protocol handling pos-pdf request for: ${filePath}`);
      return net.fetch(pathToFileURL(filePath).toString());
    } catch (error) {
      console.error('Error in pos-pdf protocol handler:', error);
      return new Response('Not Found', { status: 404 });
    }
  });
  createMainWindow();
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    dataSourceConfigurator.close();
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createMainWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
// Check for updates and notify the user
autoUpdater.checkForUpdatesAndNotify();